// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IngestConnection.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "IngestConnection.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Beam {
namespace Ftl {
namespace Ingest {
namespace Messages {
namespace Connection {
class ConnectDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Connect> {
} _Connect_default_instance_;
class Connect_ResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Connect_Response> {
} _Connect_Response_default_instance_;

namespace protobuf_IngestConnection_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect, clientprotocolversion_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect_Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect_Response, serverprotocolversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect_Response, statuscode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Connect_Response, hmackey_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(Connect)},
  { 5, -1, sizeof(Connect_Response)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Connect_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Connect_Response_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "IngestConnection.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _Connect_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Connect_Response_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Connect_default_instance_.DefaultConstruct();
  _Connect_Response_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\026IngestConnection.proto\022#Beam.Ftl.Inges"
      "t.Messages.Connection\"^\n\007Connect\022S\n\025Clie"
      "ntProtocolVersion\030\001 \001(\01624.Beam.Ftl.Inges"
      "t.Messages.Connection.ProtocolVersion\"\276\001"
      "\n\020Connect_Response\022S\n\025ServerProtocolVers"
      "ion\030\001 \001(\01624.Beam.Ftl.Ingest.Messages.Con"
      "nection.ProtocolVersion\022D\n\nStatusCode\030\002 "
      "\001(\01620.Beam.Ftl.Ingest.Messages.Connectio"
      "n.StatusCodes\022\017\n\007HmacKey\030\003 \001(\t*!\n\017Protoc"
      "olVersion\022\006\n\002V0\020\000\022\006\n\002V1\020\001*&\n\013StatusCodes"
      "\022\013\n\007SUCCESS\020\000\022\n\n\006FAILED\020\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 433);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "IngestConnection.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_IngestConnection_2eproto

const ::google::protobuf::EnumDescriptor* ProtocolVersion_descriptor() {
  protobuf_IngestConnection_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_IngestConnection_2eproto::file_level_enum_descriptors[0];
}
bool ProtocolVersion_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* StatusCodes_descriptor() {
  protobuf_IngestConnection_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_IngestConnection_2eproto::file_level_enum_descriptors[1];
}
bool StatusCodes_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Connect::kClientProtocolVersionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Connect::Connect()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_IngestConnection_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Beam.Ftl.Ingest.Messages.Connection.Connect)
}
Connect::Connect(const Connect& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clientprotocolversion_ = from.clientprotocolversion_;
  // @@protoc_insertion_point(copy_constructor:Beam.Ftl.Ingest.Messages.Connection.Connect)
}

void Connect::SharedCtor() {
  clientprotocolversion_ = 0;
  _cached_size_ = 0;
}

Connect::~Connect() {
  // @@protoc_insertion_point(destructor:Beam.Ftl.Ingest.Messages.Connection.Connect)
  SharedDtor();
}

void Connect::SharedDtor() {
}

void Connect::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Connect::descriptor() {
  protobuf_IngestConnection_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_IngestConnection_2eproto::file_level_metadata[0].descriptor;
}

const Connect& Connect::default_instance() {
  protobuf_IngestConnection_2eproto::InitDefaults();
  return *internal_default_instance();
}

Connect* Connect::New(::google::protobuf::Arena* arena) const {
  Connect* n = new Connect;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Connect::Clear() {
// @@protoc_insertion_point(message_clear_start:Beam.Ftl.Ingest.Messages.Connection.Connect)
  clientprotocolversion_ = 0;
}

bool Connect::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Beam.Ftl.Ingest.Messages.Connection.Connect)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion ClientProtocolVersion = 1;
      case 1: {
        if (tag == 8u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_clientprotocolversion(static_cast< ::Beam::Ftl::Ingest::Messages::Connection::ProtocolVersion >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Beam.Ftl.Ingest.Messages.Connection.Connect)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Beam.Ftl.Ingest.Messages.Connection.Connect)
  return false;
#undef DO_
}

void Connect::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Beam.Ftl.Ingest.Messages.Connection.Connect)
  // .Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion ClientProtocolVersion = 1;
  if (this->clientprotocolversion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->clientprotocolversion(), output);
  }

  // @@protoc_insertion_point(serialize_end:Beam.Ftl.Ingest.Messages.Connection.Connect)
}

::google::protobuf::uint8* Connect::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Beam.Ftl.Ingest.Messages.Connection.Connect)
  // .Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion ClientProtocolVersion = 1;
  if (this->clientprotocolversion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->clientprotocolversion(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Beam.Ftl.Ingest.Messages.Connection.Connect)
  return target;
}

size_t Connect::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Beam.Ftl.Ingest.Messages.Connection.Connect)
  size_t total_size = 0;

  // .Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion ClientProtocolVersion = 1;
  if (this->clientprotocolversion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->clientprotocolversion());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Connect::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Beam.Ftl.Ingest.Messages.Connection.Connect)
  GOOGLE_DCHECK_NE(&from, this);
  const Connect* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Connect>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Beam.Ftl.Ingest.Messages.Connection.Connect)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Beam.Ftl.Ingest.Messages.Connection.Connect)
    MergeFrom(*source);
  }
}

void Connect::MergeFrom(const Connect& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Beam.Ftl.Ingest.Messages.Connection.Connect)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.clientprotocolversion() != 0) {
    set_clientprotocolversion(from.clientprotocolversion());
  }
}

void Connect::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Beam.Ftl.Ingest.Messages.Connection.Connect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Connect::CopyFrom(const Connect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Beam.Ftl.Ingest.Messages.Connection.Connect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Connect::IsInitialized() const {
  return true;
}

void Connect::Swap(Connect* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Connect::InternalSwap(Connect* other) {
  std::swap(clientprotocolversion_, other->clientprotocolversion_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Connect::GetMetadata() const {
  protobuf_IngestConnection_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_IngestConnection_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Connect

// .Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion ClientProtocolVersion = 1;
void Connect::clear_clientprotocolversion() {
  clientprotocolversion_ = 0;
}
::Beam::Ftl::Ingest::Messages::Connection::ProtocolVersion Connect::clientprotocolversion() const {
  // @@protoc_insertion_point(field_get:Beam.Ftl.Ingest.Messages.Connection.Connect.ClientProtocolVersion)
  return static_cast< ::Beam::Ftl::Ingest::Messages::Connection::ProtocolVersion >(clientprotocolversion_);
}
void Connect::set_clientprotocolversion(::Beam::Ftl::Ingest::Messages::Connection::ProtocolVersion value) {
  
  clientprotocolversion_ = value;
  // @@protoc_insertion_point(field_set:Beam.Ftl.Ingest.Messages.Connection.Connect.ClientProtocolVersion)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Connect_Response::kServerProtocolVersionFieldNumber;
const int Connect_Response::kStatusCodeFieldNumber;
const int Connect_Response::kHmacKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Connect_Response::Connect_Response()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_IngestConnection_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
}
Connect_Response::Connect_Response(const Connect_Response& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  hmackey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hmackey().size() > 0) {
    hmackey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hmackey_);
  }
  ::memcpy(&serverprotocolversion_, &from.serverprotocolversion_,
    reinterpret_cast<char*>(&statuscode_) -
    reinterpret_cast<char*>(&serverprotocolversion_) + sizeof(statuscode_));
  // @@protoc_insertion_point(copy_constructor:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
}

void Connect_Response::SharedCtor() {
  hmackey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&serverprotocolversion_, 0, reinterpret_cast<char*>(&statuscode_) -
    reinterpret_cast<char*>(&serverprotocolversion_) + sizeof(statuscode_));
  _cached_size_ = 0;
}

Connect_Response::~Connect_Response() {
  // @@protoc_insertion_point(destructor:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  SharedDtor();
}

void Connect_Response::SharedDtor() {
  hmackey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Connect_Response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Connect_Response::descriptor() {
  protobuf_IngestConnection_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_IngestConnection_2eproto::file_level_metadata[1].descriptor;
}

const Connect_Response& Connect_Response::default_instance() {
  protobuf_IngestConnection_2eproto::InitDefaults();
  return *internal_default_instance();
}

Connect_Response* Connect_Response::New(::google::protobuf::Arena* arena) const {
  Connect_Response* n = new Connect_Response;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Connect_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  hmackey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&serverprotocolversion_, 0, reinterpret_cast<char*>(&statuscode_) -
    reinterpret_cast<char*>(&serverprotocolversion_) + sizeof(statuscode_));
}

bool Connect_Response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion ServerProtocolVersion = 1;
      case 1: {
        if (tag == 8u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_serverprotocolversion(static_cast< ::Beam::Ftl::Ingest::Messages::Connection::ProtocolVersion >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Beam.Ftl.Ingest.Messages.Connection.StatusCodes StatusCode = 2;
      case 2: {
        if (tag == 16u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_statuscode(static_cast< ::Beam::Ftl::Ingest::Messages::Connection::StatusCodes >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string HmacKey = 3;
      case 3: {
        if (tag == 26u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hmackey()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->hmackey().data(), this->hmackey().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Beam.Ftl.Ingest.Messages.Connection.Connect_Response.HmacKey"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  return false;
#undef DO_
}

void Connect_Response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  // .Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion ServerProtocolVersion = 1;
  if (this->serverprotocolversion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->serverprotocolversion(), output);
  }

  // .Beam.Ftl.Ingest.Messages.Connection.StatusCodes StatusCode = 2;
  if (this->statuscode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->statuscode(), output);
  }

  // string HmacKey = 3;
  if (this->hmackey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hmackey().data(), this->hmackey().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Beam.Ftl.Ingest.Messages.Connection.Connect_Response.HmacKey");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->hmackey(), output);
  }

  // @@protoc_insertion_point(serialize_end:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
}

::google::protobuf::uint8* Connect_Response::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  // .Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion ServerProtocolVersion = 1;
  if (this->serverprotocolversion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->serverprotocolversion(), target);
  }

  // .Beam.Ftl.Ingest.Messages.Connection.StatusCodes StatusCode = 2;
  if (this->statuscode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->statuscode(), target);
  }

  // string HmacKey = 3;
  if (this->hmackey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hmackey().data(), this->hmackey().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Beam.Ftl.Ingest.Messages.Connection.Connect_Response.HmacKey");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->hmackey(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  return target;
}

size_t Connect_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  size_t total_size = 0;

  // string HmacKey = 3;
  if (this->hmackey().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hmackey());
  }

  // .Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion ServerProtocolVersion = 1;
  if (this->serverprotocolversion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->serverprotocolversion());
  }

  // .Beam.Ftl.Ingest.Messages.Connection.StatusCodes StatusCode = 2;
  if (this->statuscode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->statuscode());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Connect_Response::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  GOOGLE_DCHECK_NE(&from, this);
  const Connect_Response* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Connect_Response>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
    MergeFrom(*source);
  }
}

void Connect_Response::MergeFrom(const Connect_Response& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.hmackey().size() > 0) {

    hmackey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hmackey_);
  }
  if (from.serverprotocolversion() != 0) {
    set_serverprotocolversion(from.serverprotocolversion());
  }
  if (from.statuscode() != 0) {
    set_statuscode(from.statuscode());
  }
}

void Connect_Response::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Connect_Response::CopyFrom(const Connect_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Beam.Ftl.Ingest.Messages.Connection.Connect_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Connect_Response::IsInitialized() const {
  return true;
}

void Connect_Response::Swap(Connect_Response* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Connect_Response::InternalSwap(Connect_Response* other) {
  hmackey_.Swap(&other->hmackey_);
  std::swap(serverprotocolversion_, other->serverprotocolversion_);
  std::swap(statuscode_, other->statuscode_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Connect_Response::GetMetadata() const {
  protobuf_IngestConnection_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_IngestConnection_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Connect_Response

// .Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion ServerProtocolVersion = 1;
void Connect_Response::clear_serverprotocolversion() {
  serverprotocolversion_ = 0;
}
::Beam::Ftl::Ingest::Messages::Connection::ProtocolVersion Connect_Response::serverprotocolversion() const {
  // @@protoc_insertion_point(field_get:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.ServerProtocolVersion)
  return static_cast< ::Beam::Ftl::Ingest::Messages::Connection::ProtocolVersion >(serverprotocolversion_);
}
void Connect_Response::set_serverprotocolversion(::Beam::Ftl::Ingest::Messages::Connection::ProtocolVersion value) {
  
  serverprotocolversion_ = value;
  // @@protoc_insertion_point(field_set:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.ServerProtocolVersion)
}

// .Beam.Ftl.Ingest.Messages.Connection.StatusCodes StatusCode = 2;
void Connect_Response::clear_statuscode() {
  statuscode_ = 0;
}
::Beam::Ftl::Ingest::Messages::Connection::StatusCodes Connect_Response::statuscode() const {
  // @@protoc_insertion_point(field_get:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.StatusCode)
  return static_cast< ::Beam::Ftl::Ingest::Messages::Connection::StatusCodes >(statuscode_);
}
void Connect_Response::set_statuscode(::Beam::Ftl::Ingest::Messages::Connection::StatusCodes value) {
  
  statuscode_ = value;
  // @@protoc_insertion_point(field_set:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.StatusCode)
}

// string HmacKey = 3;
void Connect_Response::clear_hmackey() {
  hmackey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Connect_Response::hmackey() const {
  // @@protoc_insertion_point(field_get:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.HmacKey)
  return hmackey_.GetNoArena();
}
void Connect_Response::set_hmackey(const ::std::string& value) {
  
  hmackey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.HmacKey)
}
#if LANG_CXX11
void Connect_Response::set_hmackey(::std::string&& value) {
  
  hmackey_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.HmacKey)
}
#endif
void Connect_Response::set_hmackey(const char* value) {
  
  hmackey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.HmacKey)
}
void Connect_Response::set_hmackey(const char* value, size_t size) {
  
  hmackey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.HmacKey)
}
::std::string* Connect_Response::mutable_hmackey() {
  
  // @@protoc_insertion_point(field_mutable:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.HmacKey)
  return hmackey_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Connect_Response::release_hmackey() {
  // @@protoc_insertion_point(field_release:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.HmacKey)
  
  return hmackey_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Connect_Response::set_allocated_hmackey(::std::string* hmackey) {
  if (hmackey != NULL) {
    
  } else {
    
  }
  hmackey_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hmackey);
  // @@protoc_insertion_point(field_set_allocated:Beam.Ftl.Ingest.Messages.Connection.Connect_Response.HmacKey)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Connection
}  // namespace Messages
}  // namespace Ingest
}  // namespace Ftl
}  // namespace Beam

// @@protoc_insertion_point(global_scope)
