// Code generated by protoc-gen-go.
// source: IngestConnection.proto
// DO NOT EDIT!

/*
Package Beam_Ftl_Ingest_Messages_Connection is a generated protocol buffer package.

It is generated from these files:
	IngestConnection.proto

It has these top-level messages:
	Connect
	Connect_Response
*/
package Beam_Ftl_Ingest_Messages_Connection

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtocolVersion int32

const (
	ProtocolVersion_V0 ProtocolVersion = 0
	ProtocolVersion_V1 ProtocolVersion = 1
)

var ProtocolVersion_name = map[int32]string{
	0: "V0",
	1: "V1",
}
var ProtocolVersion_value = map[string]int32{
	"V0": 0,
	"V1": 1,
}

func (x ProtocolVersion) String() string {
	return proto.EnumName(ProtocolVersion_name, int32(x))
}
func (ProtocolVersion) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusCodes int32

const (
	StatusCodes_SUCCESS StatusCodes = 0
	StatusCodes_FAILED  StatusCodes = 1
)

var StatusCodes_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILED",
}
var StatusCodes_value = map[string]int32{
	"SUCCESS": 0,
	"FAILED":  1,
}

func (x StatusCodes) String() string {
	return proto.EnumName(StatusCodes_name, int32(x))
}
func (StatusCodes) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Connect struct {
	ClientProtocolVersion ProtocolVersion `protobuf:"varint,1,opt,name=ClientProtocolVersion,enum=Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion" json:"ClientProtocolVersion,omitempty"`
}

func (m *Connect) Reset()                    { *m = Connect{} }
func (m *Connect) String() string            { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()               {}
func (*Connect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Connect) GetClientProtocolVersion() ProtocolVersion {
	if m != nil {
		return m.ClientProtocolVersion
	}
	return ProtocolVersion_V0
}

type Connect_Response struct {
	ServerProtocolVersion ProtocolVersion `protobuf:"varint,1,opt,name=ServerProtocolVersion,enum=Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion" json:"ServerProtocolVersion,omitempty"`
	StatusCode            StatusCodes     `protobuf:"varint,2,opt,name=StatusCode,enum=Beam.Ftl.Ingest.Messages.Connection.StatusCodes" json:"StatusCode,omitempty"`
	HmacKey               string          `protobuf:"bytes,3,opt,name=HmacKey" json:"HmacKey,omitempty"`
}

func (m *Connect_Response) Reset()                    { *m = Connect_Response{} }
func (m *Connect_Response) String() string            { return proto.CompactTextString(m) }
func (*Connect_Response) ProtoMessage()               {}
func (*Connect_Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Connect_Response) GetServerProtocolVersion() ProtocolVersion {
	if m != nil {
		return m.ServerProtocolVersion
	}
	return ProtocolVersion_V0
}

func (m *Connect_Response) GetStatusCode() StatusCodes {
	if m != nil {
		return m.StatusCode
	}
	return StatusCodes_SUCCESS
}

func (m *Connect_Response) GetHmacKey() string {
	if m != nil {
		return m.HmacKey
	}
	return ""
}

func init() {
	proto.RegisterType((*Connect)(nil), "Beam.Ftl.Ingest.Messages.Connection.Connect")
	proto.RegisterType((*Connect_Response)(nil), "Beam.Ftl.Ingest.Messages.Connection.Connect_Response")
	proto.RegisterEnum("Beam.Ftl.Ingest.Messages.Connection.ProtocolVersion", ProtocolVersion_name, ProtocolVersion_value)
	proto.RegisterEnum("Beam.Ftl.Ingest.Messages.Connection.StatusCodes", StatusCodes_name, StatusCodes_value)
}

func init() { proto.RegisterFile("IngestConnection.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf3, 0xcc, 0x4b, 0x4f,
	0x2d, 0x2e, 0x71, 0xce, 0xcf, 0xcb, 0x4b, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x52, 0x76, 0x4a, 0x4d, 0xcc, 0xd5, 0x73, 0x2b, 0xc9, 0xd1, 0x83, 0x28, 0xd0,
	0xf3, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x43, 0x28, 0x55, 0x2a, 0xe5, 0x62, 0x87,
	0xf2, 0x84, 0xb2, 0xb8, 0x44, 0x9d, 0x73, 0x32, 0x53, 0xf3, 0x4a, 0x02, 0x40, 0xda, 0x93, 0xf3,
	0x73, 0xc2, 0x52, 0x8b, 0x8a, 0x33, 0xf3, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x4c,
	0xf4, 0x88, 0x30, 0x4f, 0x0f, 0x4d, 0x6f, 0x10, 0x76, 0x23, 0x95, 0x5e, 0x31, 0x72, 0x09, 0x40,
	0x75, 0xc5, 0x07, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x82, 0x1c, 0x10, 0x9c, 0x5a, 0x54,
	0x96, 0x5a, 0x44, 0x55, 0x07, 0x60, 0x35, 0x52, 0x28, 0x80, 0x8b, 0x2b, 0xb8, 0x24, 0xb1, 0xa4,
	0xb4, 0xd8, 0x39, 0x3f, 0x25, 0x55, 0x82, 0x09, 0x6c, 0x81, 0x01, 0x51, 0x16, 0x20, 0xb4, 0x15,
	0x07, 0x21, 0x99, 0x21, 0x24, 0xc1, 0xc5, 0xee, 0x91, 0x9b, 0x98, 0xec, 0x9d, 0x5a, 0x29, 0xc1,
	0xac, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x6a, 0x29, 0x72, 0xf1, 0xa3, 0x5b, 0xcf, 0xc6, 0xc5,
	0x14, 0x66, 0x20, 0xc0, 0x00, 0xa6, 0x0d, 0x05, 0x18, 0xb5, 0xd4, 0xb8, 0xb8, 0x91, 0xcc, 0x15,
	0xe2, 0xe6, 0x62, 0x0f, 0x0e, 0x75, 0x76, 0x76, 0x0d, 0x0e, 0x16, 0x60, 0x10, 0xe2, 0xe2, 0x62,
	0x73, 0x73, 0xf4, 0xf4, 0x71, 0x75, 0x11, 0x60, 0x4c, 0x62, 0x03, 0x47, 0xad, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xe8, 0x37, 0x6d, 0x4e, 0xf4, 0x01, 0x00, 0x00,
}
